const restaurantData = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "707910",
      name: "Natthu's",
      uuid: "106b10db-ae59-43bd-844a-d15fc49ad1bc",
      city: "53",
      area: "Phoenix Mall",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "3d549758556358d75e3ce6a6f6c2eb0f",
      cuisines: ["Chinese"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 2.799999952316284,
      slugs: {
        restaurant: "natthu's-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "Basement, rajrani tower, oppt. Phoenix mall, Pilibhit Bypass Rd, North City Extension, Bareilly, Uttar Pradesh 243122, India",
      locality: "Pilibhit Bypass Rd",
      parentId: 423181,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6751206~p=1~eid=00000188-3cda-e19d-64aa-e7530015015b",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "ABOVE ₹500",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "707910",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 2.799999952316284,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "669729",
      name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
      uuid: "3772cb38-4940-4c22-a7e9-ef3c1563b306",
      city: "53",
      area: "Phoenix Mall",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "909daf097e30cd01d8fd121ddc6de2f6",
      cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 17,
      minDeliveryTime: 17,
      maxDeliveryTime: 17,
      slaString: "17 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant:
          "kwality-walls-frozen-dessert-and-ice-cream-shop-phoenix-mall-phoenix-mall-3",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "Shreya Enclave Pilibhit Bypass Road Dohra Behing MJPRU Near Sunrise Phase 2 Bareilly Uttar Pradesh",
      locality: "Shyam distti Bareilly zone 4",
      parentId: 582,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "669729",
        deliveryTime: 17,
        minDeliveryTime: 17,
        maxDeliveryTime: 17,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "669168",
      name: "The Mayra's Cafe",
      uuid: "ef4bd27f-cce3-433e-ba2e-51bae8c4b067",
      city: "53",
      area: "Phoenix Mall",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "e40e9fc6162274b3e8ab2f4a36459332",
      cuisines: [
        "Beverages",
        "Italian-American",
        "Chinese",
        "Fast Food",
        "Snacks",
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 0.5,
      slugs: {
        restaurant: "the-mayra's-cafe-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "242, 2, Dohra Road, opposite Rudraksh Apartment, Suresh Sharma Nagar, Bareilly, Uttar Pradesh 243006, India",
      locality: "Suresh Sharma Nagar",
      parentId: 401154,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "669168",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 0.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "99039",
      name: "Bala Ji (Pack & Go)",
      uuid: "fc24be1c-a793-423b-b4bf-dda17c7febc9",
      city: "53",
      area: "Model Town",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "vgfcjjfiri2j577j3gwg",
      cuisines: ["North Indian", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      slaString: "36 MINS",
      lastMileTravel: 5,
      slugs: {
        restaurant: "balaji-pack-and-go-dd-puram-dd-puram",
        city: "bareilly",
      },
      cityState: "53",
      address: "A-363/4 Rajendra Nagar Bareilly UP",
      locality: "Rajendra Nagar",
      parentId: 40493,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6573394~p=4~eid=00000188-3cda-e19d-64aa-e75400150440",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹299",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "99039",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        lastMileTravel: 5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.5",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "430165",
      name: "New Aryans Restaurant",
      uuid: "eacd4299-cc70-441d-b06a-804426027fb2",
      city: "53",
      area: "Green Park Colony",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "ioguh7bytnb5oxjwb4fp",
      cuisines: ["North Indian", "Thalis", "Snacks", "American"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 21,
      minDeliveryTime: 21,
      maxDeliveryTime: 21,
      slaString: "21 MINS",
      lastMileTravel: 1,
      slugs: {
        restaurant: "new-aryans-restaurant-phoenix-mall-phoenix-mall-2",
        city: "bareilly",
      },
      cityState: "53",
      address: "Tulsi Nagar Pilibhit Bye Pass Bareilly UP 243001",
      locality: "Tulsi Nagar",
      parentId: 236137,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "FREE ITEM",
        subHeader: "",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "430165",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "291882",
      name: "Bajrang Dhaba Family Dhaba Restaurant",
      uuid: "12153cfe-6f48-49bc-abda-06b7d96c67a9",
      city: "53",
      area: "Nawada",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "vh3b0ylzi7be9gcdgh2g",
      cuisines: ["North Indian"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 1.399999976158142,
      slugs: {
        restaurant:
          "bajrang-dhaba-family-dhaba-restaurant-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address: "SANJAY NAGAR TIRAHA OPP. SURYA ENCLAVE BAREILLY UP 243001",
      locality: "Sanjay Nagar",
      parentId: 39790,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹299",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "291882",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 1.399999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "545261",
      name: "Sharma Bakery",
      uuid: "7c12eb64-14ad-4f09-9ba6-145640a308f5",
      city: "53",
      area: "Trimurti Road Sanjay Nagar",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "zlp0it2rihltzuumswt6",
      cuisines: ["Bakery", "Desserts"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 34,
      minDeliveryTime: 34,
      maxDeliveryTime: 34,
      slaString: "34 MINS",
      lastMileTravel: 2.5999999046325684,
      slugs: {
        restaurant: "sharma-bakery-dd-puram-dd-puram",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "Trimurti Road Near Chetan Vidya Mandir School Sanjay Nagar Bareilly Uttar Pradesh",
      locality: "Sanjay Nagar",
      parentId: 182034,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6830892~p=7~eid=00000188-3cda-e19d-64aa-e75500150721",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "545261",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.4",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "709991",
      name: "Sanjay Dhaba",
      uuid: "30557740-c3c8-4ea0-811b-4e2b6d0be210",
      city: "53",
      area: "Phoenix Mall",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "fb3be3440f81b88157f50c9485e8c127",
      cuisines: ["North Indian", "Thalis", "Snacks"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: "33 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "sanjay-dhaba-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "UNIVERSITY GATE PILIBHIT BYPASS ROAD BAREILLY UTTAR PRADESH 243001",
      locality: "Bypass Road",
      parentId: 324783,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "709991",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "665714",
      name: "Rangrezz Kitchen",
      uuid: "0053f8e7-2dcb-4997-83d6-f7e050592b55",
      city: "53",
      area: "Nawada",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "0cae8c84524bba11107db4cff4c5add0",
      cuisines: ["North Indian", "Chinese", "Biryani"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: "30 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "rangrezz-kitchen-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "BICHPURI ROAD NEAR ROHILKHAND MEDICAL COLLEGE BAREILLY UTTAR PRADESH 243006",
      locality: "Suresh Sharma Nagar",
      parentId: 399140,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "ABOVE ₹650",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "665714",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.6",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "87734",
      name: "Shree Laxmi Hindu Hotel",
      uuid: "8c06e5bc-39c0-4e21-be91-b3e538c3fc46",
      city: "53",
      area: "Civil Lines",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "brkstz1qp0cdi5qqrqx8",
      cuisines: ["North Indian"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 38,
      minDeliveryTime: 38,
      maxDeliveryTime: 38,
      slaString: "38 MINS",
      lastMileTravel: 7,
      slugs: {
        restaurant: "shri-laxmi-hindu-hotel-civil-lines-civil-lines",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "Near Dharmashala Junction, Tiraka Mal Gardem, Mal Godam Road, Civil Lines, Bareilly, Uttar Pradesh 243001, India",
      locality: "Mal Godam Road",
      parentId: 186639,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3400,
        message: "",
        title: "Delivery Charge",
        amount: "3400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6577620~p=10~eid=00000188-3cda-e19d-64aa-e75600150a6f",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹299",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "87734",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        lastMileTravel: 7,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.7",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "458259",
      name: "Ananda-Food Court",
      uuid: "8fbd5d77-a6f0-4db4-abb9-147d3f1380f5",
      city: "53",
      area: "Green Park Colony",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "pmskx0eskslwzqkrjadl",
      cuisines: [
        "Indian",
        "Continental",
        "South Indian",
        "North Indian",
        "Chinese",
        "Desserts",
        "Beverages",
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      slaString: "23 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "ananda--the-food-court-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "158/19, Pashupati Vihar, Opp MJPR University Main Gate, ZONE- 10, Bareilly, Uttar Pradesh-243001",
      locality: "Pashupati Vihar",
      parentId: 274911,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "458259",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "354330",
      name: "Punjabi Fusion Restaurant",
      uuid: "f43354e4-9e84-497a-bcd8-fd4a94c9c3d3",
      city: "53",
      area: "Pashupati Vihar Colony",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "ims9zt1dj2fiwqu24lek",
      cuisines: ["Chinese", "Indian"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: "33 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "punjabi-fusion-restaurant-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "C/O ADIL ANSARI TULSI NAGAR PILIBHIT BYPASS ROAD BAREILLY UP 243006",
      locality: "Phoenix Mall",
      parentId: 162295,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "354330",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "2.8",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "115629",
      name: "Chinese Xpress",
      uuid: "a97a2fb0-6009-4262-bc6a-a19bad4f9fe2",
      city: "53",
      area: "Mahanagar Colony",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "rb8bvppcltxidrbiftpf",
      cuisines: ["Chinese", "Beverages", "Continental"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "chinese-x-press-dd-puram-civil-lines",
        city: "bareilly",
      },
      cityState: "53",
      address: "2nd Floor Food Court, Phoenix Mall",
      locality: "Phoenix United Mall",
      parentId: 9014,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6579379~p=13~eid=00000188-3cda-e19d-64aa-e75700150d60",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "15% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "115629",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.2",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "434393",
      name: "Gopal Pizza Point",
      uuid: "50b98e03-55ea-46b7-bd82-e95a179fca8a",
      city: "53",
      area: "Suresh Sharma Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "yqrggboyfsm4jblfnefp",
      cuisines: ["Pizzas"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "gopal-pizza-point-phoenix-mall-phoenix-mall",
        city: "bareilly",
      },
      cityState: "53",
      address:
        "SHOP PLOT N0.5 PART ONE AREA 7.20 SQMT NAVADA JOGIYAN SURESH SHARMA NAGAR BAREILLY UP 243006",
      locality: "Joginawada Road",
      parentId: 261806,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "",
        subHeader: "",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "434393",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "86393",
      name: "Pizzitalia",
      uuid: "9453c345-ee90-4e29-bcc2-b1712ecd1d39",
      city: "53",
      area: "Suresh Sharma Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "gjfkemmbtw5wftprwt5y",
      cuisines: ["Pizzas", "Italian"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "pizzitalia-rajendra-nagar-dd-puram",
        city: "bareilly",
      },
      cityState: "53",
      address: "Suresh Sharma Nagar Chauraha Pilibhit Byepass Road Bareilly UP",
      locality: "Joginawada Road",
      parentId: 4803,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹299",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "86393",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
];

export { restaurantData };
